first commit
AlexForJava/HomeWork5 pull request #1
Opened 2019-03-07 20:05 UTC by AlexForJava

2019-03-08 20:37 UTC, Taniann requested changes
good
but add case with dividing

2019-03-08 20:37 UTC, Taniann commented on .gitignore
> +*.iml
that file shouldn't be in homework PR

2019-03-08 20:37 UTC, Taniann commented on src/com/gmail/chernii/oleksii/Main.java
> +                                                    (action == '#' && first != 0) ? ((first + second) / first * 1.0 + 117.) : 0;
better make user informed that there is no such action instead of returning 0

2019-03-09 12:36 UTC, AlexForJava commented
Sorry, I forget about .gitignore

Thank you 

8 марта 2019, 22:37:59, от "Алексей" <hqq@ukr.net>:

@Taniann requested changes on this pull request.

good
but add case with dividing

In .gitignore:

> @@ -21,3 +21,5 @@
 
 # virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml
 hs_err_pid*
+*.iml
that file shouldn't be in homework PR

In src/com/gmail/chernii/oleksii/Main.java:

> @@ -0,0 +1,32 @@
+package com.gmail.chernii.oleksii;
+
+import java.util.Scanner;
+
+/**
+ * Created by Space on 07.03.2019.
+ */
+public class Main {
+    private static Calculator calculator = (first, second, action) ->
+            (action == '+') ? (first + second) :
+                    (action == '*') ? (first * second) :
+                            (action == '-') ? (first - second) :
+                                    (action == '$' && second != 0) ? (Math.pow(first, 1 / second)) :
+                                            (action == '^') ? (Math.pow(first, second)) :
+                                                    (action == '#' && first != 0) ? ((first + second) / first * 1.0 + 117.) : 0;
better make user informed that there is no such action instead of returning 0

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-03-10 13:55 UTC, closed without merging